### ISSUE TITLE
pngtiler

### ISSUE THREAD

**Issue by edemaine** [edemaine/svgtiler#10]
This may be a separate project, but I'd like to create an analogous project where the tiled objects are PNG (or other raster formats), and so is the output (as in 8-bit games).

**Comment by jbosboom** [comment]
I would like this for making figures about the thing described in [this Coauthor post](https://coauthor.csail.mit.edu/6.890/m/KbEsZ2rDgWDgm5au6).  (I guess I could try auto-tracing software to make a vector version.)

**Comment by edemaine** [comment]
An easy form of this would be to support `.png` filenames as a symbol specification (in the same way that an `.svg` filename can be specified as a symbol), and autoconvert that into
```svg
<image xlink:href="filename.png" style="image-rendering: optimizeSpeed" ...x, y, width, image.../>
```
The output would be an SVG that depends on these PNGs being the same directory (but if converted to PDF via `-p` that would include everything).  Is this interesting to you, or would you rather a direct PNG output?

**Comment by jbosboom** [comment]
That's good enough.  If I should really need a PNG output, I can just rasterize the PDF.

Instead of using an image href, we could have an image symbol embedding the image as a data URL, and then `<use>` it, so the resulting SVG would be larger but not depend on other files.  (Probably not worth it.)

**Comment by edemaine** [comment]
I assumed this was possible. Do you know how to do it?

Not sure which approach is best.  Probably command-line option choosing between the two would be nice.

**Comment by edemaine** [comment]
v1.4.0 adds support for `.png` files as a symbol specifier.  Width/height equals the image dimensions in pixels.  If all images have the same size, this should work as desired.  There's an example in `examples/tetris`.

**Comment by edemaine** [comment]
v1.4.1 also adds PNG export (via Inkscape). Let me know how it works for you.
