### ISSUE TITLE
Filenames

### ISSUE THREAD

**Issue by combinatronics** [edemaine/svgtiler#15]
There are two issues related to the use of filenames in the ASCII mapping files.

1.  If the user runs 'svgtiler' without arguments then they are instructed that "Each line is <symbol-name><space><raw SVG or filename.svg>".  This makes the desired format of the filename a bit opaque.  Should it be filename.svg or 'filename.svg' or "filename.svg" or <filename.svg> or any of those options without the file extension or with the entire path.  Based on error messages it seems that <filename.svg> is the desired format.

2. The above filename feature doesn't seem to work.  In particular, I can copy and paste the contents of filename.svg in the place of <filename.svg> and turn a non-working example into a working example.  More specifically, the resulting output svg file has the following code which doesn't seem correct:

  <symbol id="sk">
    <square.svg/>
  </symbol>

Minimal example attached.
[filename.zip](https://github.com/edemaine/svgtiler/files/749207/filename.zip)

**Comment by edemaine** [comment]
This was a bug -- turns out I never tested this functionality!  But version 1.1.1 fixes it.

The intended format is in fact `filename` (no decorations around it).  I've clarified the documentation accordingly too.
