### ISSUE TITLE
Full command-line examples

### ISSUE THREAD

**Issue by combinatronics** [edemaine/svgtiler#16]
The help is a bit short on specific command-line examples.  For example, there could be a sample usage section added.  In particular, the following example would have been very helpful:

  svgtiler map.txt drawing.asc

This is an issue due in part to the multitude of allowable formats; new users may not be able to quickly determine if they need to supply a mapping file as .txt and .js and .coffee or simply one of those options.

**Comment by edemaine** [comment]
Thanks for the report, and sorry this took me so long to get to!
