### ISSUE TITLE
Better Unicode support

### ISSUE THREAD

**Issue by edemaine** [edemaine/svgtiler#35]
@diomidov points out that Unicode support in `.asc` (ASCII art) is suboptimal, because JavaScript doesn't understand what is a "single" Unicode symbol: some symbols are represented by a combining character and a base character.  `Array.from` is apparently a partial solution to this, but for full emoji support (which seems useful here), a library like [stringz](https://github.com/sallar/stringz#toarray) seems like the best solution.

**Comment by diomidov** [comment]
[This library](https://github.com/orling/grapheme-splitter) seems to use the official unicode text segmentation rules ([UAX #29](https://unicode.org/reports/tr29/#Grapheme_Cluster_Boundary_Rules)) instead of a questionable regex. It also has 60 times as many weekly downloads on npm.

**Comment by edemaine** [comment]
Added in 1.7.0! Let me know if you encounter any issues.
