### ISSUE TITLE
<style>/<defs> support

### ISSUE THREAD

**Issue by edemaine** [edemaine/svgtiler#38]
It would be nice to be able to define global CSS rules via `<style>` tag, and global objects like gradients via `<defs>` tag, but we currently don't have anywhere to put global definitions.  I see a few options:

1. A special symbol like `global` or maybe `svgtiler:global` (to avoid conflicts) that can contain such definitions.
2. JS/CS files could define a top-level symbol like `global` that could be detected (I think) in addition to the main return value (object or function mapping).
3. JS/CS could make an API call like `svgtiler.def(...)` or modify API data like `svgtiler.defs.push(...)`.
4. JS/CS files could write `export defs = <defs>...</defs>`, now that we support `export`
5. New input file type `file.svg` that can have `<defs>` (or `<symbol>`s?) in it, which gets directly included.
6. Allow individual symbols to include `<style>` or `<defs>` tags (outside of `<symbol>`s, similar to #33) that get assembled into a global set of definitions, deduplicating CSS rules and defs with identical ids.

The idea for the last option is that rules are often local to the (various versions of) a single symbol, and this way you can just include the rules you need for this particular figure. One example would be if the symbol SVG was extracted from an Illustrator file, which often has a `<style>` tag. But this also often isn't the case, e.g., all line types might be the same, or the definitions of `-` and `|` might share a lot. Not sure what's best...

**Comment by edemaine** [comment]
A new approach: allow a new file type, `.css`, in the command line. We can allow `.styl` too! The contents go straight into a `<style >` block. This makes it easy to run a tileset through different style files, which is how CSS is supposed to work.

**Comment by diomidov** [comment]
Sometimes I want to use a `<marker>` or `<clipPath>` in my symbol, where the shape depends on symbol's neighbors. Currently I have to make sure that they have distinct names, which is a pain.

Possible solution: an `addDef(...)` function which takes an svg ovject such as `<symbol>`/`<marker>`/`<clipPath>`/etc, adds it to the global `<defs>` with a unique `id` *if it is not already there*, and returns that `id`.

**Comment by edemaine** [comment]
Nice idea!

Alternatively, we could use the `export defs = <defs>...</defs>` option, and automatically remove any symbols/markers/etc. that aren't referred to via `href`.

Oh, but I see your point is to automatically generate unique IDs for dynamic markers *inside symbols*. That does is definitely an advantage of your approach!
