### ISSUE TITLE
[Enhancement Request] <hide></hide> messages 

### ISSUE THREAD

**Issue by sualehasif996** [edemaine/svgtiler#39]
It would be nice to be able to hide specific parts of the message while writing a response. This encourages clarity and hide pictures/ long and bashy proofs of lemmas inside the message and focus on the key ideas outside. This also makes browsing easier. Ideally you can also recursively put hide tags inside of hide tags. That allows alot of flexibility in how this is used.

(I am not sure but it may also help loading the webpage faster if we don't render the hidden images/ messages until the user clicks the unhide button)

Example pictures/screenshots from artofproblemsolving.com attached below.

**Comment by sualehasif996** [comment]
The claims hidden:
<img width="991" alt="Screen Shot 2019-06-18 at 11 50 50 AM" src="https://user-images.githubusercontent.com/28659689/59699470-9ec4f600-91bf-11e9-932b-ee6243aa6cd8.png">

One of the claims expanded:
<img width="991" alt="Screen Shot 2019-06-18 at 11 51 13 AM" src="https://user-images.githubusercontent.com/28659689/59699472-9ec4f600-91bf-11e9-8bc1-2c2376fc547d.png">


You can also recursively put hide tags inside of hide tags. That allows alot of flexibility in how this is used.

**Comment by edemaine** [comment]
@sualehasif996 Did you mean to post this to Coauthor instead of SVG Tiler?

**Comment by sualehasif996** [comment]
Oops, I messed up. I moved the issues to Coauthor.
