### ISSUE TITLE
xlink:href in preact tags

### ISSUE THREAD

**Issue by diomidov** [edemaine/svgtiler#41]
```
svgtiler puuull.coffee svgtiler/*.asc
* puuull.coffee
/home/diomidov/.npm-global/lib/node_modules/svgtiler/node_modules/coffeescript/lib/coffeescript/coffeescript.js:60
        throw helpers.updateSyntaxError(err, code, options.filename);
        ^

puuull.coffee:7:17: error: unexpected :
    <image xlink:href="data:image/png;base64,#{base64}" />
```

It works if I explicitly call preact.h:
```
    preact.h('image', {
        'xlink:href': "data:image/png;base64,#{base64}"
    })
```

**Comment by edemaine** [comment]
Thanks for the report. This sounds like a problem with the Babel transpiler, though I thought I passed the argument to explicitly allow namespaces like this.. Will investigate.

**Comment by edemaine** [comment]
This turns out to be a bug in CoffeeScript; it works fine in JSX.  Once https://github.com/jashkenas/coffeescript/pull/5218 is merged, this will be fixed.  If it's urgent, I can switch the coffeescript version to my fork.

**Comment by diomidov** [comment]
Not urgent, I used the preact.h workaround.
