### ISSUE TITLE
Wrong viewBox in polyomino example

### ISSUE THREAD

**Issue by diomidov** [edemaine/svgtiler#55]
Currently it's `<symbol viewBox="-10 10 20 20" overflowBox="-12.5 -12.5 25 25" style="overflow: visible">` but it should probably be `<symbol viewBox="-10 -10 20 20" overflowBox="-12.5 -12.5 25 25" style="overflow: visible">`.

**Comment by edemaine** [comment]
Thanks for spotting this!  Fixed.
